sudo: false
jdk: openjdk8
language: java
script: mvn --show-version -Dmaven.javadoc.skip=true -P update-site verify
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    skip_cleanup: true
    script: bash .travis/deploy.sh
    on:
      branch: master