os: linux
sudo: false
dist: trusty
jdk: oraclejdk8
language: java
script: mvn clean verify -U -X --show-version -Dmaven.javadoc.skip=true -P update-site
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    skip_cleanup: true
    script: bash .travis/deploy.sh
    on:
      branch: master