/*
 * generated by Xtext 2.13.0
 */
package lang.ide

import com.google.inject.Guice
import lang.IotlangRuntimeModule
import lang.IotlangStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class IotlangIdeSetup extends IotlangStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new IotlangRuntimeModule, new IotlangIdeModule))
	}
	
}
