/**
 * generated by Xtext 2.13.0
 */
package lang.iotlang.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import lang.iotlang.Datatype;
import lang.iotlang.IotlangFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Datatype</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class DatatypeTest extends TestCase {

	/**
	 * The fixture for this Datatype test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Datatype fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(DatatypeTest.class);
	}

	/**
	 * Constructs a new Datatype test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DatatypeTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Datatype test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(Datatype fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Datatype test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Datatype getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(IotlangFactory.eINSTANCE.createDatatype());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //DatatypeTest
