/**
 * generated by Xtext 2.13.0
 */
package lang.iotlang.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import lang.iotlang.InstanceChannel;
import lang.iotlang.IotlangFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Instance Channel</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class InstanceChannelTest extends TestCase {

	/**
	 * The fixture for this Instance Channel test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InstanceChannel fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(InstanceChannelTest.class);
	}

	/**
	 * Constructs a new Instance Channel test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public InstanceChannelTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Instance Channel test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(InstanceChannel fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Instance Channel test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InstanceChannel getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(IotlangFactory.eINSTANCE.createInstanceChannel());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //InstanceChannelTest
