/**
 * generated by Xtext 2.13.0
 */
package lang.iotlang.impl;

import java.util.Collection;

import lang.iotlang.Bind;
import lang.iotlang.InstanceBus;
import lang.iotlang.InstanceThing;
import lang.iotlang.IotlangPackage;
import lang.iotlang.PlatformAnnotation;
import lang.iotlang.Topic;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bind</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link lang.iotlang.impl.BindImpl#getName <em>Name</em>}</li>
 *   <li>{@link lang.iotlang.impl.BindImpl#getThinginst <em>Thinginst</em>}</li>
 *   <li>{@link lang.iotlang.impl.BindImpl#getDirection <em>Direction</em>}</li>
 *   <li>{@link lang.iotlang.impl.BindImpl#getBusInst <em>Bus Inst</em>}</li>
 *   <li>{@link lang.iotlang.impl.BindImpl#getChannels <em>Channels</em>}</li>
 *   <li>{@link lang.iotlang.impl.BindImpl#getAnnotations <em>Annotations</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BindImpl extends MinimalEObjectImpl.Container implements Bind
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getThinginst() <em>Thinginst</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThinginst()
   * @generated
   * @ordered
   */
  protected InstanceThing thinginst;

  /**
   * The default value of the '{@link #getDirection() <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDirection()
   * @generated
   * @ordered
   */
  protected static final String DIRECTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDirection() <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDirection()
   * @generated
   * @ordered
   */
  protected String direction = DIRECTION_EDEFAULT;

  /**
   * The cached value of the '{@link #getBusInst() <em>Bus Inst</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBusInst()
   * @generated
   * @ordered
   */
  protected InstanceBus busInst;

  /**
   * The cached value of the '{@link #getChannels() <em>Channels</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChannels()
   * @generated
   * @ordered
   */
  protected EList<Topic> channels;

  /**
   * The cached value of the '{@link #getAnnotations() <em>Annotations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnnotations()
   * @generated
   * @ordered
   */
  protected EList<PlatformAnnotation> annotations;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BindImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IotlangPackage.Literals.BIND;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IotlangPackage.BIND__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InstanceThing getThinginst()
  {
    if (thinginst != null && thinginst.eIsProxy())
    {
      InternalEObject oldThinginst = (InternalEObject)thinginst;
      thinginst = (InstanceThing)eResolveProxy(oldThinginst);
      if (thinginst != oldThinginst)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, IotlangPackage.BIND__THINGINST, oldThinginst, thinginst));
      }
    }
    return thinginst;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InstanceThing basicGetThinginst()
  {
    return thinginst;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setThinginst(InstanceThing newThinginst)
  {
    InstanceThing oldThinginst = thinginst;
    thinginst = newThinginst;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IotlangPackage.BIND__THINGINST, oldThinginst, thinginst));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDirection()
  {
    return direction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDirection(String newDirection)
  {
    String oldDirection = direction;
    direction = newDirection;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IotlangPackage.BIND__DIRECTION, oldDirection, direction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InstanceBus getBusInst()
  {
    if (busInst != null && busInst.eIsProxy())
    {
      InternalEObject oldBusInst = (InternalEObject)busInst;
      busInst = (InstanceBus)eResolveProxy(oldBusInst);
      if (busInst != oldBusInst)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, IotlangPackage.BIND__BUS_INST, oldBusInst, busInst));
      }
    }
    return busInst;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InstanceBus basicGetBusInst()
  {
    return busInst;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBusInst(InstanceBus newBusInst)
  {
    InstanceBus oldBusInst = busInst;
    busInst = newBusInst;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IotlangPackage.BIND__BUS_INST, oldBusInst, busInst));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Topic> getChannels()
  {
    if (channels == null)
    {
      channels = new EObjectResolvingEList<Topic>(Topic.class, this, IotlangPackage.BIND__CHANNELS);
    }
    return channels;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<PlatformAnnotation> getAnnotations()
  {
    if (annotations == null)
    {
      annotations = new EObjectContainmentEList<PlatformAnnotation>(PlatformAnnotation.class, this, IotlangPackage.BIND__ANNOTATIONS);
    }
    return annotations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IotlangPackage.BIND__ANNOTATIONS:
        return ((InternalEList<?>)getAnnotations()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IotlangPackage.BIND__NAME:
        return getName();
      case IotlangPackage.BIND__THINGINST:
        if (resolve) return getThinginst();
        return basicGetThinginst();
      case IotlangPackage.BIND__DIRECTION:
        return getDirection();
      case IotlangPackage.BIND__BUS_INST:
        if (resolve) return getBusInst();
        return basicGetBusInst();
      case IotlangPackage.BIND__CHANNELS:
        return getChannels();
      case IotlangPackage.BIND__ANNOTATIONS:
        return getAnnotations();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IotlangPackage.BIND__NAME:
        setName((String)newValue);
        return;
      case IotlangPackage.BIND__THINGINST:
        setThinginst((InstanceThing)newValue);
        return;
      case IotlangPackage.BIND__DIRECTION:
        setDirection((String)newValue);
        return;
      case IotlangPackage.BIND__BUS_INST:
        setBusInst((InstanceBus)newValue);
        return;
      case IotlangPackage.BIND__CHANNELS:
        getChannels().clear();
        getChannels().addAll((Collection<? extends Topic>)newValue);
        return;
      case IotlangPackage.BIND__ANNOTATIONS:
        getAnnotations().clear();
        getAnnotations().addAll((Collection<? extends PlatformAnnotation>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IotlangPackage.BIND__NAME:
        setName(NAME_EDEFAULT);
        return;
      case IotlangPackage.BIND__THINGINST:
        setThinginst((InstanceThing)null);
        return;
      case IotlangPackage.BIND__DIRECTION:
        setDirection(DIRECTION_EDEFAULT);
        return;
      case IotlangPackage.BIND__BUS_INST:
        setBusInst((InstanceBus)null);
        return;
      case IotlangPackage.BIND__CHANNELS:
        getChannels().clear();
        return;
      case IotlangPackage.BIND__ANNOTATIONS:
        getAnnotations().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IotlangPackage.BIND__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case IotlangPackage.BIND__THINGINST:
        return thinginst != null;
      case IotlangPackage.BIND__DIRECTION:
        return DIRECTION_EDEFAULT == null ? direction != null : !DIRECTION_EDEFAULT.equals(direction);
      case IotlangPackage.BIND__BUS_INST:
        return busInst != null;
      case IotlangPackage.BIND__CHANNELS:
        return channels != null && !channels.isEmpty();
      case IotlangPackage.BIND__ANNOTATIONS:
        return annotations != null && !annotations.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", direction: ");
    result.append(direction);
    result.append(')');
    return result.toString();
  }

} //BindImpl
