/**
 * generated by Xtext 2.13.0
 */
package lang.iotlang.impl;

import lang.iotlang.InternalTransition;
import lang.iotlang.IotlangPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Internal Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InternalTransitionImpl extends HandlerImpl implements InternalTransition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InternalTransitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IotlangPackage.Literals.INTERNAL_TRANSITION;
  }

} //InternalTransitionImpl
