/**
 * generated by Xtext 2.13.0
 */
package lang.iotlang.impl;

import lang.iotlang.IotlangPackage;
import lang.iotlang.PubSub;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pub Sub</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PubSubImpl extends ChannelImpl implements PubSub
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PubSubImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IotlangPackage.Literals.PUB_SUB;
  }

} //PubSubImpl
