/**
 * generated by Xtext 2.13.0
 */
package lang.iotlang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bind</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lang.iotlang.Bind#getName <em>Name</em>}</li>
 *   <li>{@link lang.iotlang.Bind#getThinginst <em>Thinginst</em>}</li>
 *   <li>{@link lang.iotlang.Bind#getDirection <em>Direction</em>}</li>
 *   <li>{@link lang.iotlang.Bind#getBusInst <em>Bus Inst</em>}</li>
 *   <li>{@link lang.iotlang.Bind#getChannels <em>Channels</em>}</li>
 *   <li>{@link lang.iotlang.Bind#getAnnotations <em>Annotations</em>}</li>
 * </ul>
 *
 * @see lang.iotlang.IotlangPackage#getBind()
 * @model
 * @generated
 */
public interface Bind extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see lang.iotlang.IotlangPackage#getBind_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link lang.iotlang.Bind#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Thinginst</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Thinginst</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Thinginst</em>' reference.
   * @see #setThinginst(InstanceThing)
   * @see lang.iotlang.IotlangPackage#getBind_Thinginst()
   * @model
   * @generated
   */
  InstanceThing getThinginst();

  /**
   * Sets the value of the '{@link lang.iotlang.Bind#getThinginst <em>Thinginst</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Thinginst</em>' reference.
   * @see #getThinginst()
   * @generated
   */
  void setThinginst(InstanceThing value);

  /**
   * Returns the value of the '<em><b>Direction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Direction</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direction</em>' attribute.
   * @see #setDirection(String)
   * @see lang.iotlang.IotlangPackage#getBind_Direction()
   * @model
   * @generated
   */
  String getDirection();

  /**
   * Sets the value of the '{@link lang.iotlang.Bind#getDirection <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direction</em>' attribute.
   * @see #getDirection()
   * @generated
   */
  void setDirection(String value);

  /**
   * Returns the value of the '<em><b>Bus Inst</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bus Inst</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bus Inst</em>' reference.
   * @see #setBusInst(InstanceBus)
   * @see lang.iotlang.IotlangPackage#getBind_BusInst()
   * @model
   * @generated
   */
  InstanceBus getBusInst();

  /**
   * Sets the value of the '{@link lang.iotlang.Bind#getBusInst <em>Bus Inst</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bus Inst</em>' reference.
   * @see #getBusInst()
   * @generated
   */
  void setBusInst(InstanceBus value);

  /**
   * Returns the value of the '<em><b>Channels</b></em>' reference list.
   * The list contents are of type {@link lang.iotlang.Topic}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Channels</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Channels</em>' reference list.
   * @see lang.iotlang.IotlangPackage#getBind_Channels()
   * @model
   * @generated
   */
  EList<Topic> getChannels();

  /**
   * Returns the value of the '<em><b>Annotations</b></em>' containment reference list.
   * The list contents are of type {@link lang.iotlang.PlatformAnnotation}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Annotations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotations</em>' containment reference list.
   * @see lang.iotlang.IotlangPackage#getBind_Annotations()
   * @model containment="true"
   * @generated
   */
  EList<PlatformAnnotation> getAnnotations();

} // Bind
