/**
 * generated by Xtext 2.13.0
 */
package lang.iotlang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Channeling</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lang.iotlang.Channeling#getName <em>Name</em>}</li>
 *   <li>{@link lang.iotlang.Channeling#getThinginst <em>Thinginst</em>}</li>
 *   <li>{@link lang.iotlang.Channeling#getPort <em>Port</em>}</li>
 *   <li>{@link lang.iotlang.Channeling#getDirection <em>Direction</em>}</li>
 *   <li>{@link lang.iotlang.Channeling#getSrv <em>Srv</em>}</li>
 *   <li>{@link lang.iotlang.Channeling#getBuses <em>Buses</em>}</li>
 *   <li>{@link lang.iotlang.Channeling#getChannels <em>Channels</em>}</li>
 *   <li>{@link lang.iotlang.Channeling#getAnnotations <em>Annotations</em>}</li>
 * </ul>
 *
 * @see lang.iotlang.IotlangPackage#getChanneling()
 * @model
 * @generated
 */
public interface Channeling extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see lang.iotlang.IotlangPackage#getChanneling_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link lang.iotlang.Channeling#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Thinginst</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Thinginst</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Thinginst</em>' reference.
   * @see #setThinginst(Instance)
   * @see lang.iotlang.IotlangPackage#getChanneling_Thinginst()
   * @model
   * @generated
   */
  Instance getThinginst();

  /**
   * Sets the value of the '{@link lang.iotlang.Channeling#getThinginst <em>Thinginst</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Thinginst</em>' reference.
   * @see #getThinginst()
   * @generated
   */
  void setThinginst(Instance value);

  /**
   * Returns the value of the '<em><b>Port</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Port</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' reference.
   * @see #setPort(Port)
   * @see lang.iotlang.IotlangPackage#getChanneling_Port()
   * @model
   * @generated
   */
  Port getPort();

  /**
   * Sets the value of the '{@link lang.iotlang.Channeling#getPort <em>Port</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' reference.
   * @see #getPort()
   * @generated
   */
  void setPort(Port value);

  /**
   * Returns the value of the '<em><b>Direction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Direction</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direction</em>' attribute.
   * @see #setDirection(String)
   * @see lang.iotlang.IotlangPackage#getChanneling_Direction()
   * @model
   * @generated
   */
  String getDirection();

  /**
   * Sets the value of the '{@link lang.iotlang.Channeling#getDirection <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direction</em>' attribute.
   * @see #getDirection()
   * @generated
   */
  void setDirection(String value);

  /**
   * Returns the value of the '<em><b>Srv</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Srv</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Srv</em>' reference.
   * @see #setSrv(InstanceGateway)
   * @see lang.iotlang.IotlangPackage#getChanneling_Srv()
   * @model
   * @generated
   */
  InstanceGateway getSrv();

  /**
   * Sets the value of the '{@link lang.iotlang.Channeling#getSrv <em>Srv</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Srv</em>' reference.
   * @see #getSrv()
   * @generated
   */
  void setSrv(InstanceGateway value);

  /**
   * Returns the value of the '<em><b>Buses</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Buses</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Buses</em>' reference.
   * @see #setBuses(Bus)
   * @see lang.iotlang.IotlangPackage#getChanneling_Buses()
   * @model
   * @generated
   */
  Bus getBuses();

  /**
   * Sets the value of the '{@link lang.iotlang.Channeling#getBuses <em>Buses</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Buses</em>' reference.
   * @see #getBuses()
   * @generated
   */
  void setBuses(Bus value);

  /**
   * Returns the value of the '<em><b>Channels</b></em>' reference list.
   * The list contents are of type {@link lang.iotlang.Channel}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Channels</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Channels</em>' reference list.
   * @see lang.iotlang.IotlangPackage#getChanneling_Channels()
   * @model
   * @generated
   */
  EList<Channel> getChannels();

  /**
   * Returns the value of the '<em><b>Annotations</b></em>' containment reference list.
   * The list contents are of type {@link lang.iotlang.PlatformAnnotation}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Annotations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotations</em>' containment reference list.
   * @see lang.iotlang.IotlangPackage#getChanneling_Annotations()
   * @model containment="true"
   * @generated
   */
  EList<PlatformAnnotation> getAnnotations();

} // Channeling
