/**
 * generated by Xtext 2.13.0
 */
package lang.iotlang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Composite State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lang.iotlang.CompositeState#getRegion <em>Region</em>}</li>
 *   <li>{@link lang.iotlang.CompositeState#getSession <em>Session</em>}</li>
 * </ul>
 *
 * @see lang.iotlang.IotlangPackage#getCompositeState()
 * @model
 * @generated
 */
public interface CompositeState extends State, StateContainer
{
  /**
   * Returns the value of the '<em><b>Region</b></em>' containment reference list.
   * The list contents are of type {@link lang.iotlang.Region}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Region</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Region</em>' containment reference list.
   * @see lang.iotlang.IotlangPackage#getCompositeState_Region()
   * @model containment="true"
   * @generated
   */
  EList<Region> getRegion();

  /**
   * Returns the value of the '<em><b>Session</b></em>' containment reference list.
   * The list contents are of type {@link lang.iotlang.Session}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Session</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Session</em>' containment reference list.
   * @see lang.iotlang.IotlangPackage#getCompositeState_Session()
   * @model containment="true"
   * @generated
   */
  EList<Session> getSession();

} // CompositeState
