/**
 * generated by Xtext 2.13.0
 */
package lang.iotlang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Configuration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lang.iotlang.Configuration#getDomain <em>Domain</em>}</li>
 *   <li>{@link lang.iotlang.Configuration#getChannelings <em>Channelings</em>}</li>
 *   <li>{@link lang.iotlang.Configuration#getInstancegateways <em>Instancegateways</em>}</li>
 *   <li>{@link lang.iotlang.Configuration#getInstances <em>Instances</em>}</li>
 *   <li>{@link lang.iotlang.Configuration#getConnectors <em>Connectors</em>}</li>
 *   <li>{@link lang.iotlang.Configuration#getPropassigns <em>Propassigns</em>}</li>
 * </ul>
 *
 * @see lang.iotlang.IotlangPackage#getConfiguration()
 * @model
 * @generated
 */
public interface Configuration extends NamedElement, AnnotatedElement
{
  /**
   * Returns the value of the '<em><b>Domain</b></em>' containment reference list.
   * The list contents are of type {@link lang.iotlang.Domain}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Domain</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Domain</em>' containment reference list.
   * @see lang.iotlang.IotlangPackage#getConfiguration_Domain()
   * @model containment="true"
   * @generated
   */
  EList<Domain> getDomain();

  /**
   * Returns the value of the '<em><b>Channelings</b></em>' containment reference list.
   * The list contents are of type {@link lang.iotlang.Channeling}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Channelings</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Channelings</em>' containment reference list.
   * @see lang.iotlang.IotlangPackage#getConfiguration_Channelings()
   * @model containment="true"
   * @generated
   */
  EList<Channeling> getChannelings();

  /**
   * Returns the value of the '<em><b>Instancegateways</b></em>' containment reference list.
   * The list contents are of type {@link lang.iotlang.InstanceGateway}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Instancegateways</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instancegateways</em>' containment reference list.
   * @see lang.iotlang.IotlangPackage#getConfiguration_Instancegateways()
   * @model containment="true"
   * @generated
   */
  EList<InstanceGateway> getInstancegateways();

  /**
   * Returns the value of the '<em><b>Instances</b></em>' containment reference list.
   * The list contents are of type {@link lang.iotlang.Instance}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Instances</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instances</em>' containment reference list.
   * @see lang.iotlang.IotlangPackage#getConfiguration_Instances()
   * @model containment="true"
   * @generated
   */
  EList<Instance> getInstances();

  /**
   * Returns the value of the '<em><b>Connectors</b></em>' containment reference list.
   * The list contents are of type {@link lang.iotlang.AbstractConnector}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Connectors</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connectors</em>' containment reference list.
   * @see lang.iotlang.IotlangPackage#getConfiguration_Connectors()
   * @model containment="true"
   * @generated
   */
  EList<AbstractConnector> getConnectors();

  /**
   * Returns the value of the '<em><b>Propassigns</b></em>' containment reference list.
   * The list contents are of type {@link lang.iotlang.ConfigPropertyAssign}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Propassigns</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Propassigns</em>' containment reference list.
   * @see lang.iotlang.IotlangPackage#getConfiguration_Propassigns()
   * @model containment="true"
   * @generated
   */
  EList<ConfigPropertyAssign> getPropassigns();

} // Configuration
