/**
 * generated by Xtext 2.13.0
 */
package lang.iotlang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Connect</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lang.iotlang.Connect#getName <em>Name</em>}</li>
 *   <li>{@link lang.iotlang.Connect#getThingInstance <em>Thing Instance</em>}</li>
 *   <li>{@link lang.iotlang.Connect#getDirection <em>Direction</em>}</li>
 *   <li>{@link lang.iotlang.Connect#getPtpInstance <em>Ptp Instance</em>}</li>
 *   <li>{@link lang.iotlang.Connect#getAnnotations <em>Annotations</em>}</li>
 * </ul>
 *
 * @see lang.iotlang.IotlangPackage#getConnect()
 * @model
 * @generated
 */
public interface Connect extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see lang.iotlang.IotlangPackage#getConnect_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link lang.iotlang.Connect#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Thing Instance</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Thing Instance</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Thing Instance</em>' reference.
   * @see #setThingInstance(InstanceThing)
   * @see lang.iotlang.IotlangPackage#getConnect_ThingInstance()
   * @model
   * @generated
   */
  InstanceThing getThingInstance();

  /**
   * Sets the value of the '{@link lang.iotlang.Connect#getThingInstance <em>Thing Instance</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Thing Instance</em>' reference.
   * @see #getThingInstance()
   * @generated
   */
  void setThingInstance(InstanceThing value);

  /**
   * Returns the value of the '<em><b>Direction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Direction</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direction</em>' attribute.
   * @see #setDirection(String)
   * @see lang.iotlang.IotlangPackage#getConnect_Direction()
   * @model
   * @generated
   */
  String getDirection();

  /**
   * Sets the value of the '{@link lang.iotlang.Connect#getDirection <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direction</em>' attribute.
   * @see #getDirection()
   * @generated
   */
  void setDirection(String value);

  /**
   * Returns the value of the '<em><b>Ptp Instance</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ptp Instance</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ptp Instance</em>' reference.
   * @see #setPtpInstance(InstancePtP)
   * @see lang.iotlang.IotlangPackage#getConnect_PtpInstance()
   * @model
   * @generated
   */
  InstancePtP getPtpInstance();

  /**
   * Sets the value of the '{@link lang.iotlang.Connect#getPtpInstance <em>Ptp Instance</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ptp Instance</em>' reference.
   * @see #getPtpInstance()
   * @generated
   */
  void setPtpInstance(InstancePtP value);

  /**
   * Returns the value of the '<em><b>Annotations</b></em>' containment reference list.
   * The list contents are of type {@link lang.iotlang.PlatformAnnotation}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Annotations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotations</em>' containment reference list.
   * @see lang.iotlang.IotlangPackage#getConnect_Annotations()
   * @model containment="true"
   * @generated
   */
  EList<PlatformAnnotation> getAnnotations();

} // Connect
