/**
 * generated by Xtext 2.13.0
 */
package lang.iotlang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see lang.iotlang.IotlangPackage#getEvent()
 * @model
 * @generated
 */
public interface Event extends NamedElement
{
} // Event
