/**
 * generated by Xtext 2.13.0
 */
package lang.iotlang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instance Bus</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lang.iotlang.InstanceBus#getName <em>Name</em>}</li>
 *   <li>{@link lang.iotlang.InstanceBus#getNumber <em>Number</em>}</li>
 *   <li>{@link lang.iotlang.InstanceBus#getTypeChannel <em>Type Channel</em>}</li>
 *   <li>{@link lang.iotlang.InstanceBus#getProtocol <em>Protocol</em>}</li>
 *   <li>{@link lang.iotlang.InstanceBus#getAnnotations <em>Annotations</em>}</li>
 * </ul>
 *
 * @see lang.iotlang.IotlangPackage#getInstanceBus()
 * @model
 * @generated
 */
public interface InstanceBus extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see lang.iotlang.IotlangPackage#getInstanceBus_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link lang.iotlang.InstanceBus#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Number</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute list.
   * @see lang.iotlang.IotlangPackage#getInstanceBus_Number()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getNumber();

  /**
   * Returns the value of the '<em><b>Type Channel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Channel</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Channel</em>' reference.
   * @see #setTypeChannel(Channel)
   * @see lang.iotlang.IotlangPackage#getInstanceBus_TypeChannel()
   * @model
   * @generated
   */
  Channel getTypeChannel();

  /**
   * Sets the value of the '{@link lang.iotlang.InstanceBus#getTypeChannel <em>Type Channel</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Channel</em>' reference.
   * @see #getTypeChannel()
   * @generated
   */
  void setTypeChannel(Channel value);

  /**
   * Returns the value of the '<em><b>Protocol</b></em>' reference list.
   * The list contents are of type {@link lang.iotlang.Protocol}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Protocol</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Protocol</em>' reference list.
   * @see lang.iotlang.IotlangPackage#getInstanceBus_Protocol()
   * @model
   * @generated
   */
  EList<Protocol> getProtocol();

  /**
   * Returns the value of the '<em><b>Annotations</b></em>' containment reference list.
   * The list contents are of type {@link lang.iotlang.PlatformAnnotation}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Annotations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotations</em>' containment reference list.
   * @see lang.iotlang.IotlangPackage#getInstanceBus_Annotations()
   * @model containment="true"
   * @generated
   */
  EList<PlatformAnnotation> getAnnotations();

} // InstanceBus
