/**
 * generated by Xtext 2.13.0
 */
package lang.iotlang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lang.iotlang.Instance#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see lang.iotlang.IotlangPackage#getInstance()
 * @model
 * @generated
 */
public interface Instance extends NamedElement, AnnotatedElement
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(Thing)
   * @see lang.iotlang.IotlangPackage#getInstance_Type()
   * @model
   * @generated
   */
  Thing getType();

  /**
   * Sets the value of the '{@link lang.iotlang.Instance#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(Thing value);

} // Instance
