/**
 * generated by Xtext 2.13.0
 */
package lang.iotlang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Message</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lang.iotlang.Message#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see lang.iotlang.IotlangPackage#getMessage()
 * @model
 * @generated
 */
public interface Message extends NamedElement, AnnotatedElement
{
  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link lang.iotlang.Parameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see lang.iotlang.IotlangPackage#getMessage_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

} // Message
