/**
 * generated by Xtext 2.13.0
 */
package lang.iotlang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lang.iotlang.PropertyReference#getProperty <em>Property</em>}</li>
 * </ul>
 *
 * @see lang.iotlang.IotlangPackage#getPropertyReference()
 * @model
 * @generated
 */
public interface PropertyReference extends Expression
{
  /**
   * Returns the value of the '<em><b>Property</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Property</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property</em>' reference.
   * @see #setProperty(Variable)
   * @see lang.iotlang.IotlangPackage#getPropertyReference_Property()
   * @model
   * @generated
   */
  Variable getProperty();

  /**
   * Sets the value of the '{@link lang.iotlang.PropertyReference#getProperty <em>Property</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property</em>' reference.
   * @see #getProperty()
   * @generated
   */
  void setProperty(Variable value);

} // PropertyReference
