/**
 * generated by Xtext 2.13.0
 */
package lang.iotlang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Protocol</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see lang.iotlang.IotlangPackage#getProtocol()
 * @model
 * @generated
 */
public interface Protocol extends NamedElement, AnnotatedElement
{
} // Protocol
