/**
 * generated by Xtext 2.13.0
 */
package lang.validation;

import lang.validation.AbstractIotlangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IotlangValidator extends AbstractIotlangValidator {
}
